[project]
name = "13f-db"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "0xludics", email = "contact@ludics.xyz" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []
